
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Text to speech
tts:
  - platform: google_translate
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
panel_iframe:
  mdiindex:
    title: MDI Icon
    icon: mdi:vector-square
    url: https://materialdesignicons.com/
  bt2mqtt_config:
    title: BT2MQTT Editor
    icon: mdi:file-document-edit-outline
    url: http://192.168.1.64:3218
device_tracker:
  - platform: bluetooth_le_tracker
    track_new_devices: true
