version: '3'

services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.10
    restart: always
    ports:
       - 1883:1883
       - 9001:9001
    volumes:
      - /opt/data-mosquitto/config:/mosquitto/config
      - /opt/data-mosquitto/data:/mosquitto/data
      - /opt/data-mosquitto/log:/mosquitto/log

  hassos:
    image: homeassistant/armv7-hassio-supervisor
    container_name: hassio_supervisor
    privileged: true
    restart: always
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - HOMEASSISTANT_REPOSITORY=homeassistant/raspberrypi4-homeassistant
      - SUPERVISOR_NAME=hassio_supervisor
      - SUPERVISOR_SHARE=/home/pi/hassio/data
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/hassio/data:/data
      - /home/pi/hassio/scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    depends_on:
      - mosquitto
      
#   portainer:
#     image: portainer/portainer
#     container_name: portainer
#     restart: always
#     ports:
#       - "9000:9000"
#     command: -H unix:///var/run/docker.sock
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - /home/pi/hassio/portainer:/data:rw

  bt-mqtt-gateway:
    container_name: bt-mqtt-gateway
    image: akashic0616/bt-mqtt-gateway:latest    
    restart: always
    devices:
      # the value of "/dev/input/" corresponds to an actual path on the system of Raspberry Pi 4.
      - /dev/input:/dev/input
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/bt-mqtt-gateway/config.yaml:/config.yaml
      - /opt/bt-mqtt-gateway/notbarcodereader.txt:/application/notbarcodereader.txt
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    network_mode: host
    entrypoint: ["/application/wait-for-it.sh", "127.0.0.1:8123", "--timeout=0", "--", "/bin/sh", "-c", "/start.sh" ]
    depends_on:
      - mosquitto
      - hassos
      
  bt2mqtt-configurator:
    image: "causticlab/hass-configurator-docker:arm"
    container_name: bt2mqtt-configurator
    restart: always
    privileged: true
    ports:
      - "3218:3218/tcp"
    depends_on:
      - bt-mqtt-gateway
    volumes:
      - /opt/bt2mqtt/config:/config
      - /opt/bt-mqtt-gateway:/application
